services:
 recipeapi:
    build: ./tech-test-software-engineer/RecipeApi/
    container_name: 'recipe-api'
    ports:
      - "8080:80"

 schedulingapi:
    build: ./RecipeSchedulingAPI
    container_name: 'scheduling-api'
    ports:
      - "8090:5000"
    depends_on:
      - recipeapi 
    environment: 
      # REMARK: I prefer to not rely on default settings and rather specify it explicitly 
      - ASPNETCORE_HTTP_PORTS=5000