@RecipeSchedulingAPI_HostAddress = http://localhost:5238

GET {{RecipeSchedulingAPI_HostAddress}}/api/v1/schedule
Accept: application/json

###

# Send post request with JSON body defining a list of requests
POST {{RecipeSchedulingAPI_HostAddress}}/api/v1/schedule/multiple
Content-Type: application/json

{
  "input": [
    {
      "trayNumber": 1,
      "recipeName": "Basil",
      "startDate": "2022-01-24T12:30:00.0000000Z"
    },
    {
      "trayNumber": 2,
      "recipeName": "Strawberries",
      "startDate": "2021-13-08T17:33:00.0000000Z"
    },
    {
      "trayNumber": 3,
      "recipeName": "Basil",
      "startDate": "2030-01-01T23:45:00.0000000Z"
    }
  ]
}

###


# Send post request with JSON body defining a single request
POST {{RecipeSchedulingAPI_HostAddress}}/api/v1/schedule/single
Content-Type: application/json

{
  "trayNumber": 1,
  "recipeName": "Basil",
  "startDate": "2022-01-24T12:30:00.0000000Z"
}